#!/bin/bash
set -e
set -x
PATH=/opt/spacemit-toolchain-linux-glibc-x86_64-v1.0.5/bin/:$PATH
make Q= V=1 PLATFORM=K1 CROSS_COMPILE=riscv64-unknown-linux-gnu- PLATFORM_DEFCONFIG=defconfig PLATFORM=generic ARCH=riscv

find . -name fw_dynamic.itb -exec ls -l '{}' ';'

echo sudo dd if=build/platform/generic/firmware/fw_dynamic.itb of=/dev/mmcblk0 bs=1024 seek=640
